version: "3.8"
services:
    api:
        ports:
        -   "8000:8000"
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
        -   .:/app
        environment:
            RELOAD: "True"
            DEBUG: "True"
        command: hypercorn videoverse_backend.web.application:app --bind "0.0.0.0:8000" --reload
